run:
  concurrency: 8
  deadline: 10m
  issues-exit-code: 1
  tests: false

linters-settings:
  govet:
    check-shadowing: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - experimental
  gci:
    local-prefixes: github.com/alexandear/import-gitlab-commits

linters:
  enable-all: true
  disable:
    - maligned
    - exhaustivestruct
    - exhaustruct
    - nonamedreturns
    - gomnd
    - nosnakecase
    - interfacer
    - varcheck
    - ifshort
    - structcheck
    - deadcode
    - scopelint
    - golint
    - rowserrcheck
    - wastedassign
    - goerr113

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
